---
version: '3'

volumes:
  cowrie-var:

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "22:2222"
      - "23:2223"
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
